### ISSUE TITLE
new refreshtoken on every request

### ISSUE THREAD

**Issue by scharph** [Keda87/golang-echo-jwt-rsa#1]
Thanks for sharing your project .. 
Currently trying to understand the jwt token concept and found your project on reddit

First question:

Is it state of the art to generate a new refreshtoken after every auth token renewal?

/api/auth-token

```json
{
  "accessToken": "token1", // valid 15 min
  "refreshToken": "refreshtoken1" // valid 7 days
}
```

/api/refresh-token { "refreshToken": "refreshtoken1"}

```json
{
  "accessToken": "token2",  // valid 15 min
  "refreshToken": "refreshtoken2" // valid 7 days
}

.

```
So for this example, (refreshtoken is always renewed) .. the user is logged in forever ( when the latest RT is always used)
Am i right?

**Comment by Keda87** [comment]
Hi @scharph!
Yes, that's correct! the goal is to keep users logged in on the application.

as far as I know, JWT is designed to become a short-lived token, and the refresh-token API is for requesting a new access token. because it will annoying if we have to submit username and password again and again within the application.
since we have a valid refresh token, we don't have to let our users input username and password to use the application, we just need to refresh it. Once the refreshToken expired then we let our users to login with username and password.

I realized my codes are not ready for production and only proof and concept. it should have a logic when the refreshToken is used, then it should be cannot be used again, but currently, there's no validation for that.
